name: Bug report
description: Report bugs with the data pack here. (DO NOT INCLUDE THE PRE-V2 OR PRE-1.21 AS IT'S CONSIDERED DISCONTINUED)
labels: [bug]
body:
  - type: textarea
    attributes:
      label: Describe your bug here.
    validations:
      required: true