name: Bug report
description: Report bugs with the data pack here. (ONLY FOR THE MAIN BRANCH, OTHERS ARE MOST LIKELY DISCONTINUED)
labels: [bug]
body:
  - type: textarea
    attributes:
      label: Describe your bug here.
    validations:
      required: true